version: '3.1'

volumes:
  geonetwork:
  esdata:
  pgdata:
  pglog:
  nginxlog:
  apachelog:


networks:
  gn-network:
    driver: bridge


services:
  www:
    image: nginx
    ports:
      - 80:80
    environment:
      # Only used for / redirect to default webapp
      - NGINX_PUBLIC_HOST=geodata.valenceromansagglo.fr
      - NGINX_HOST=geodata.valenceromansagglo.fr
      - NGINX_PORT=80
      - WEBAPP_CONTEXT_PATH=/catalogue

    volumes:
      - ./nginx:/etc/nginx/templates
      - nginxlog:/var/log/nginx
    depends_on:
      - geonetwork
      - qgis-server
    networks:
      - gn-network

#  www:
#    image: httpd
#    ports:
#      - 81:80
#    environment:
#      - WEBAPP_CONTEXT_PATH=/geonetwork
#    volumes:
#      - ./apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
#      - ./apache/gn-httpd.conf:/usr/local/apache2/conf/gn-httpd.conf
#      - apachelog:/usr/local/apache2/logs
#    depends_on:
#      - geonetwork
#    networks:
#      - gn-network


  database:
    image: postgis/postgis:11-2.5
    environment:
      POSTGRES_USER: catalogue
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: catalogue
    command: [ "postgres",
               "-c", "log_statement=all",
               "-c", "logging_collector=true",
               "-c", "log_file_mode=0644",
               "-c", "log_directory=/var/log/postgresql",
               "-c", "log_filename=postgresql.log" ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pglog:/var/log/postgresql
    networks:
      - gn-network


  geonetwork:
    image: geonetwork:4.2.5
    restart: always
    ports:
      - 8080:8080
    environment:
      WEBAPP_CONTEXT_PATH: /geonetwork
      DATA_DIR: /catalogue-data

      JAVA_OPTS: >-
        -Djava.security.egd=file:/dev/./urandom -Djava.awt.headless=true
        -Xms512M -Xss512M -Xmx2G -XX:+UseConcMarkSweepGC
        -Djetty.httpConfig.requestHeaderSize=32768
        -Dorg.eclipse.jetty.server.Request.maxFormContentSize=500000
      # For remote debug
      # -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005

      GN_CONFIG_PROPERTIES: >-
        -Dgeonetwork.dir=/catalogue-data
        -Dgeonetwork.formatter.dir=/catalogue-data/data/formatter
        -Dgeonetwork.schema.dir=/opt/geonetwork/WEB-INF/data/config/schema_plugins
        -Dgeonetwork.indexConfig.dir=/opt/geonetwork/WEB-INF/data/config/index
        -Des.host=elasticsearch
        -Des.protocol=http
        -Des.port=9200
        -Des.url=http://elasticsearch:9200
        -Des.username=
        -Des.password=
        -Dgeonetwork.ESFeaturesProxy.targetUri=http://elasticsearch:9200/gn-features/{_}
        -Dgeonetwork.HttpDashboardProxy.targetUri=http://kibana:5601
        -Dgeonetwork.MicroServicesProxy.targetUri=http://ogc-api-records-service:8080

      GEONETWORK_DB_TYPE: postgres
      GEONETWORK_DB_HOST: database
      GEONETWORK_DB_PORT: 5432
      GEONETWORK_DB_NAME: catalogue
      GEONETWORK_DB_USERNAME: catalogue
      GEONETWORK_DB_PASSWORD: changeme
    volumes:
      - ./catalogue-data:/catalogue-data
    depends_on:
      - elasticsearch
      - database
    networks:
      - gn-network

  ogc-api-records-service:
    image: geonetwork/gn-cloud-ogc-api-records-service:4.2.5-0
    environment:
      SPRING_PROFILES_ACTIVE: standalone
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/catalogue
      SPRING_DATASOURCE_USERNAME: catalogue
      SPRING_DATASOURCE_PASSWORD: changeme
      GN_BASEURL: https://geodata.valenceromansagglo.fr/catalogue/api
      GN_LEGACY_URL: https://geodata.valenceromansagglo.fr/catalogue
      GN_INDEX_URL: http://elasticsearch:9200
      SERVER_FORWARDHEADERSSTRATEGY: FRAMEWORK
      JAVA_OPTS: -Dfile.encoding=UTF-8

    depends_on:
      - database
      - elasticsearch
      - geonetwork
    networks:
      - gn-network




  elasticsearch:
    image: elasticsearch:7.17.10
    ports:
      - 9200:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    environment:
      ES_JAVA_OPTS: "-Xms1G -Xmx1G"
      discovery.type: single-node
    volumes:
      - esdata:/usr/share/elasticsearch/data
    networks:
      - gn-network

  kibana:
    image: kibana:7.17.10
    environment:
      SERVER_NAME: 'kibana'
      ELASTICSEARCH_URL: http://elasticsearch:9200/
      SERVER_BASEPATH: /catalogue/dashboards
      SERVER_REWRITEBASEPATH: 'false'
      KIBANA_INDEX: .dashboards
      XPACK_MONITORING_UI_CONTAINER_ELASTICSEARCH_ENABLED: 'true'
    networks:
      - gn-network

  qgis-server:
    image: qgis-server:latest
    ports:
      - 5555:5555
    hostname:
      qgis-server
    environment:
      QGIS_PROJECT_FILE: /data/osm.qgs
    volumes:
      - ./qgis-server/data:/data:ro
    networks:
      - gn-network
